name: base
channels:
  - conda-forge
  - default
dependencies:
  # - powerline-status
  # - vim
  # - prompt_toolkit
  - pygments
  # - conda-forge::ncurses
  # - python
  - black
  - pylint
  - ipython
  - ipdb
  - ipykernel
  - mypy
  - mock
  - pytest
  - pyyaml
  - yamllint
  - yq
  - shyaml
  - sqlfluff
  - shandy-sqlfmt
  # - flask
  # - xlsxwriter
  # - pandas
  # - numpy
  # - seaborn
  # - plotly
  # - matplotlib
  # - altair
  # - vega_datasets
  # - scipy
  # - scikit-learn
  # - jupyterlab
  # - jupyter
  # - beautifulsoup4
  # - openai
  # temporarily pin sqlite 3.46 so sqlite and ipython work
  - libsqlite=3.46
